import test from 'node:test';import assert from 'node:assert/strict';import {optimalEntry,probabilisticEV} from '../src/optimal-entry.mjs';import {armSensorAblation,settleSensorAblation,settleSensorAblationBars,channelEvidence} from '../src/ablation-engine.mjs';import {calibrateAssetForecast} from '../src/multiasset-calibration.mjs';import {issueBoundedAuthority,authorityHealth} from '../src/authority-controller.mjs';import {evaluatePromotion} from '../src/promotion-evaluator.mjs';
const f={pUp:.7,pDown:.15,pRange:.15,LONG:{mfe50:120,mae50:40,mae90:75},SHORT:{mfe50:55,mae50:60,mae90:100}};
test('optimal entry can emit limit and freezes price',()=>{const x=optimalEntry({side:'LONG',referencePrice:100,forecast:f});assert.equal(x.action,'LIMIT');assert.ok(x.price<100)});
test('probabilistic EV is model-derived and cost-aware',()=>assert.equal(probabilisticEV({side:'LONG',forecast:f}),65));
test('sensor ablation compares same outcome without promotion',()=>{const t=armSensorAblation({symbol:'BTCUSDT',at:'2026-01-01T00:00:00Z',channel:'funding',evidence:{value:.001,quality:'CAPTURED'},baseDecision:{action:'NO_TRADE'},challengerDecision:{action:'LONG',costBps:13}}),s=settleSensorAblation(t,{returnBps:30});assert.equal(s.incrementalNetBps,17);assert.equal(channelEvidence([s],'funding').promotionAllowed,false)});
test('multiasset model stays shadow until calibration evidence threshold',()=>{const x=calibrateAssetForecast({symbol:'ETHUSDT',forecast:f,diagnostics:{n:50,ece:.03,brier:.2}});assert.equal(x.tradeAuthority,'NONE');assert.equal(x.status,'SHADOW_ONLY')});

test('causal evaluator settles baseline and challenger on same immutable future path',()=>{const t={...armSensorAblation({symbol:'BTCUSDT',at:'2026-01-01T00:00:00Z',channel:'deltaOi',evidence:{value:1,quality:'VERIFIED'},baseDecision:{action:'NO_TRADE'},challengerDecision:{action:'LONG',costBps:13}}),referencePrice:100};const bars=[1,2,3,4].map((h,i)=>({t:1767229200+i*3600,o:100,h:102+i,l:99,c:101+i}));const s=settleSensorAblationBars(t,{bars,settledAt:'2026-01-01T05:00:00Z',source:'test-bars'});assert.equal(s.world.bars.length,4);assert.equal(s.baselineNetBps,0);assert.ok(s.challengerNetBps>0);assert.ok(s.world.pathHash);assert.equal(s.tradeAuthority,'NONE')});

test('promotion evaluator fails closed on insufficient prospective evidence',()=>{const rows=[{status:'SETTLED',channel:'deltaOi',incrementalNetBps:10,didActionChange:true,featureCutoff:'2026-01-01T00:00:00Z',armedAt:'2026-01-01T00:00:01Z',world:{pathHash:'x'},tradeAuthority:'NONE',baselineResult:{maeBps:20},challengerResult:{maeBps:10},regime:'trend'}];const e=evaluatePromotion(rows,{channel:'deltaOi'});assert.equal(e.promote,false);assert.equal(e.status,'CONTINUE_SHADOW');assert.equal(e.checks.enoughN,false)});

test('authority is bounded, shadow-only and revocable on degradation',()=>{const license=issueBoundedAuthority({promote:true,meanIncrementalNetBps:30,bootstrap95:{low:5},tailDelta95Bps:-2},{artifactHash:'abc',channel:'deltaOi'});assert.equal(license.realMoneyAuthority,false);assert.deepEqual(license.scope.symbols,['BTCUSDT']);const recent=Array.from({length:20},()=>({status:'SETTLED',channel:'deltaOi',incrementalNetBps:-10,baselineResult:{maeBps:20},challengerResult:{maeBps:25}}));const h=authorityHealth(license,recent);assert.equal(h.valid,false);assert.equal(h.reason,'EDGE_DEGRADATION')});
