import crypto from 'node:crypto';
const hash=x=>crypto.createHash('sha256').update(JSON.stringify(x)).digest('hex');
const bps=(x,e)=>(x/e-1)*10000;
export function armSensorAblation({symbol,at,horizonHours=4,baseDecision,channel,evidence,challengerDecision,featureCutoff=at,preregisteredMetrics=['netBps','mfeBps','maeBps','firstTouch']}){
 if(!symbol||!at||!channel)throw Error('INVALID_ABLATION_TRIAL');
 const evidenceHash=hash(evidence),trialId=hash({symbol,at,horizonHours,channel,evidenceHash,baseDecision,challengerDecision}).slice(0,24);
 return{trialId,symbol,armedAt:at,featureCutoff,horizonHours,channel,evidenceHash,evidenceObservedAt:evidence?.observedAt||null,evidenceQuality:evidence?.quality||'UNKNOWN',baseline:baseDecision,challenger:challengerDecision,didActionChange:baseDecision?.action!==challengerDecision?.action,preregisteredMetrics,status:'ARMED',admission:'OBSERVE_ONLY',tradeAuthority:'NONE'};
}
function scorePath(d,bars,entry,costBps=13){if(!d?.action||d.action==='NO_TRADE')return{action:'NO_TRADE',netBps:0,mfeBps:0,maeBps:0,firstTouch:'NONE'};const long=d.action==='LONG',hi=Math.max(...bars.map(x=>x.h)),lo=Math.min(...bars.map(x=>x.l)),last=bars.at(-1).c,mfe=long?bps(hi,entry):-bps(lo,entry),mae=long?-bps(lo,entry):bps(hi,entry),terminal=bps(last,entry)*(long?1:-1);let firstTouch='NONE';const tp=d.takeProfit??d.tp,sl=d.stopLoss??d.sl;if(Number.isFinite(tp)&&Number.isFinite(sl))for(const x of bars){const ht=long?x.h>=tp:x.l<=tp,hs=long?x.l<=sl:x.h>=sl;if(ht&&hs){firstTouch='AMBIGUOUS';break}if(ht){firstTouch='TP';break}if(hs){firstTouch='SL';break}}return{action:d.action,netBps:+(terminal-(d.costBps??costBps)).toFixed(3),terminalBps:+terminal.toFixed(3),mfeBps:+mfe.toFixed(3),maeBps:+mae.toFixed(3),firstTouch}}
export function settleSensorAblationBars(trial,{bars,settledAt,source}){if(!Array.isArray(bars)||bars.length<trial.horizonHours)throw Error('INCOMPLETE_FUTURE_PATH');const future=bars.slice(0,trial.horizonHours),entry=trial.referencePrice;if(!Number.isFinite(entry))throw Error('MISSING_REFERENCE_PRICE');const baseline=scorePath(trial.baseline,future,entry),challenger=scorePath(trial.challenger,future,entry);return{...trial,status:'SETTLED',settledAt,world:{source,bars:future.map(x=>({t:x.t,o:x.o,h:x.h,l:x.l,c:x.c})),pathHash:hash(future)},baselineResult:baseline,challengerResult:challenger,baselineNetBps:baseline.netBps,challengerNetBps:challenger.netBps,incrementalNetBps:+(challenger.netBps-baseline.netBps).toFixed(3),incrementalMfeBps:+(challenger.mfeBps-baseline.mfeBps).toFixed(3),incrementalMaeBps:+(challenger.maeBps-baseline.maeBps).toFixed(3),tradeAuthority:'NONE'};}
export function settleSensorAblation(trial,outcome){const score=d=>d?.action==='NO_TRADE'||!d?.action?0:(d.action==='LONG'?1:-1)*(outcome.returnBps||0)-(d.costBps||0),b=score(trial.baseline),c=score(trial.challenger);return{...trial,status:'SETTLED',settledAt:outcome.settledAt||new Date().toISOString(),outcome,baselineNetBps:+b.toFixed(3),challengerNetBps:+c.toFixed(3),incrementalNetBps:+(c-b).toFixed(3),tradeAuthority:'NONE'};}
export function channelEvidence(rows,channel){const r=rows.filter(x=>x.channel===channel&&x.status==='SETTLED');if(!r.length)return{channel,n:0,status:'INSUFFICIENT_EVIDENCE',promotionAllowed:false};const ds=r.map(x=>x.incrementalNetBps),mean=ds.reduce((a,b)=>a+b,0)/ds.length,changed=r.filter(x=>x.didActionChange);return{channel,n:r.length,meanIncrementalNetBps:+mean.toFixed(3),actionChangeRate:+(changed.length/r.length).toFixed(3),causal:changed.length>0,status:'OBSERVATION_ONLY',promotionAllowed:false};}
