import crypto from 'node:crypto';
import {putEvidence} from './ledger.mjs';
import {recordLineage,hashEvidence} from './lineage.mjs';
import {runDeskAgents} from './desk-agents.mjs';
const sha=x=>crypto.createHash('sha256').update(JSON.stringify(x)).digest('hex'),ALPHA=new Set(['PRICENET','MICROSTRUCTURE','DERIVATIVES','OPPORTUNITY']);
export function aggregateDesk(opinions,{consensus}={}){const active=opinions.filter(x=>ALPHA.has(x.agent)&&x.vote!=='ABSTAIN'),bull=active.filter(x=>x.vote==='LONG').reduce((s,x)=>s+x.confidence,0),bear=active.filter(x=>x.vote==='SHORT').reduce((s,x)=>s+x.confidence,0),edge=(bull-bear)/(bull+bear||1),skeptic=opinions.find(x=>x.agent==='SKEPTIC');let action=Math.abs(edge)>=.22?(edge>0?'LONG':'SHORT'):'NO_TRADE',reason='INDEPENDENT_ALPHA_EDGE';if(!consensus?.verified){action='NO_TRADE';reason='FUTURES_CONSENSUS_VETO'}if((skeptic?.confidence??0)>=.75){action='NO_TRADE';reason='SKEPTIC_VETO'}return{action,reason,edge:+edge.toFixed(4),bull:+bull.toFixed(4),bear:+bear.toFixed(4),alphaAgents:active.map(x=>x.agent)}}
export function deskAblations(opinions,consensus){return [...ALPHA].map(agent=>{const a=aggregateDesk(opinions.filter(x=>x.agent!==agent),{consensus});return{removedAgent:agent,action:a.action,edge:a.edge}})}
export function executionModel({action,referencePrice,futuresState}){if(!['LONG','SHORT'].includes(action)||!Number.isFinite(referencePrice))return null;const s=futuresState?.ok?futuresState.state:null,halfSpread=Math.max(0,Number(s?.spreadBps||0)/2),impact=Math.min(8,Math.abs(Number(s?.depthImbalance||0))*1.5+Math.abs(Number(s?.flowImbalance||0))*1.5),feeBps=Number(process.env.DESK_TAKER_FEE_BPS||5),slippageBps=+(halfSpread+impact).toFixed(3),costBps=+(feeBps+slippageBps).toFixed(3),signed=action==='LONG'?1:-1,fill=referencePrice*(1+signed*slippageBps/10000);return{model:'shadow-taker-v1',feeBps,slippageBps,costBps,expectedFill:+fill.toFixed(2),horizonHours:4}}
export async function runDesk({px,consensus,futuresState,context,marketOpportunity,referencePrice,observedAt}){const opinions=runDeskAgents({px,consensus,futuresState,context,marketOpportunity}),a=aggregateDesk(opinions,{consensus}),execution=executionModel({action:a.action,referencePrice,futuresState}),ablations=deskAblations(opinions,consensus),upstreamHashes=[hashEvidence({kind:'pricenet',px}),hashEvidence({kind:'futures_consensus',consensus}),hashEvidence({kind:'futures_state',futuresState}),hashEvidence({kind:'market_opportunity',marketOpportunity})];const decision={desk_version:'kisa-desk-v3-execution',...a,reference_price:referencePrice,observed_at:observedAt,execution_mode:'SHADOW_ONLY',execution,ablations,opinions};const id=sha(decision);decision.desk_decision_id=id;await putEvidence('desk_decision',id,decision);decision.lineageHash=await recordLineage('desk_decision',id,decision,{parentHashes:upstreamHashes});if(execution)await putEvidence('desk_shadow_trade',id,{deskDecisionId:id,action:a.action,referencePrice,execution,openedAt:observedAt,status:'OPEN'});await putEvidence('desk_ablation',id,{deskDecisionId:id,observedAt,ablations});return decision}
