import crypto from 'node:crypto';
import {initLedger,putEvidence} from './ledger.mjs';
import pg from 'pg';
const {Pool}=pg; let pool;
export const LINEAGE_SCHEMA_VERSION=2;
const db=()=>{if(!process.env.DATABASE_URL)return null;pool??=new Pool({connectionString:process.env.DATABASE_URL,ssl:false,max:2});return pool};
const stable=x=>Array.isArray(x)?x.map(stable):x&&typeof x==='object'?Object.fromEntries(Object.keys(x).sort().map(k=>[k,stable(x[k])])):x;
export const hashEvidence=x=>crypto.createHash('sha256').update(JSON.stringify(stable(x))).digest('hex');
export async function initLineage(){const p=db();if(!p)return false;await initLedger();await p.query(`CREATE TABLE IF NOT EXISTS evidence_lineage(event_type text NOT NULL,event_id text NOT NULL,event_hash text NOT NULL,parent_hashes text[] NOT NULL DEFAULT '{}',status text NOT NULL DEFAULT 'CLEAN',taint_root text,created_at timestamptz NOT NULL DEFAULT now(),schema_version integer NOT NULL DEFAULT 1,hash_version text NOT NULL DEFAULT 'LEGACY_STABLE_JSON_V1',PRIMARY KEY(event_type,event_id)); ALTER TABLE evidence_lineage ADD COLUMN IF NOT EXISTS schema_version integer NOT NULL DEFAULT 1; ALTER TABLE evidence_lineage ADD COLUMN IF NOT EXISTS hash_version text NOT NULL DEFAULT 'LEGACY_STABLE_JSON_V1'; CREATE TABLE IF NOT EXISTS lineage_schema_migrations(version integer PRIMARY KEY,applied_at timestamptz NOT NULL DEFAULT now(),description text NOT NULL); INSERT INTO lineage_schema_migrations(version,description) VALUES(1,'legacy evidence_lineage identity preserved'),(2,'versioned lineage metadata; legacy hashes preserved') ON CONFLICT(version) DO NOTHING; CREATE INDEX IF NOT EXISTS evidence_lineage_hash_idx ON evidence_lineage(event_hash); CREATE INDEX IF NOT EXISTS evidence_lineage_parents_idx ON evidence_lineage USING gin(parent_hashes);`);return true}
export async function recordLineage(eventType,eventId,payload,{parentHashes=[],schemaVersion=LINEAGE_SCHEMA_VERSION,hashVersion='LEGACY_STABLE_JSON_V1'}={}){const eventHash=hashEvidence({eventType,eventId,payload,parentHashes});const p=db();if(p){await initLineage();await p.query('INSERT INTO evidence_lineage(event_type,event_id,event_hash,parent_hashes,status,schema_version,hash_version) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(event_type,event_id) DO NOTHING',[eventType,eventId,eventHash,parentHashes,'CLEAN',schemaVersion,hashVersion])}await putEvidence('lineage_record',eventHash,{eventType,eventId,eventHash,parentHashes,schemaVersion,hashVersion,status:'CLEAN',recordedAt:new Date().toISOString()});return eventHash}
export async function invalidateAndTaint({eventHash,reason}){const p=db();if(!p)throw Error('LINEAGE_POSTGRES_REQUIRED');await initLineage();const r=await p.query(`WITH RECURSIVE d AS (SELECT event_hash FROM evidence_lineage WHERE event_hash=$1 UNION SELECT e.event_hash FROM evidence_lineage e JOIN d ON d.event_hash=ANY(e.parent_hashes)) UPDATE evidence_lineage SET status='TAINTED',taint_root=$1 WHERE event_hash IN (SELECT event_hash FROM d) RETURNING event_hash,event_type,event_id`,[eventHash]);const body={operation:'INVALIDATE_TAINT',taintRoot:eventHash,reason,descendants:r.rows,at:new Date().toISOString()};await putEvidence('lineage_invalidation',hashEvidence(body),body);return body}
export async function cleanAncestor(eventHash){const p=db();if(!p)throw Error('LINEAGE_POSTGRES_REQUIRED');await initLineage();const r=await p.query(`WITH RECURSIVE a AS (SELECT event_hash,parent_hashes,status,0 depth FROM evidence_lineage WHERE event_hash=$1 UNION ALL SELECT e.event_hash,e.parent_hashes,e.status,a.depth+1 FROM evidence_lineage e JOIN a ON e.event_hash=ANY(a.parent_hashes)) SELECT event_hash,depth FROM a WHERE status='CLEAN' ORDER BY depth ASC LIMIT 1`,[eventHash]);return r.rows[0]??null}
export async function verifyReplay({taintRoot,ancestorHash,replayedEvidence,policyDigest}){const replayHash=hashEvidence({ancestorHash,replayedEvidence,policyDigest});const body={operation:'CUT_REPLAY_VERIFY',taintRoot,ancestorHash,replayHash,policyDigest,status:'VERIFIED_RECONSTRUCTION',verifiedAt:new Date().toISOString()};await putEvidence('lineage_reconstruction',replayHash,body);return body}

export async function lineageSchemaState(){const p=db();if(!p)throw Error('LINEAGE_POSTGRES_REQUIRED');await initLineage();const r=await p.query('SELECT version,applied_at,description FROM lineage_schema_migrations ORDER BY version');return {currentVersion:LINEAGE_SCHEMA_VERSION,migrations:r.rows}}
export async function readLineageByIds(ids=[]){const p=db();if(!p)throw Error('LINEAGE_POSTGRES_REQUIRED');await initLineage();const r=await p.query('SELECT event_type,event_id,event_hash,parent_hashes,status,taint_root,schema_version,hash_version FROM evidence_lineage WHERE event_id = ANY($1::text[]) ORDER BY created_at ASC',[ids]);return r.rows}
