const num=Number,clip=(x,a,b)=>Math.max(a,Math.min(b,x)),ret=(a,b)=>a>0?10000*(b/a-1):0;
async function j(u){const r=await fetch(u,{headers:{'user-agent':'KISASIGNALS/3.1','accept':'application/json'},signal:AbortSignal.timeout(8000)});if(!r.ok)throw Error('HTTP_'+r.status);return r.json()}
function score({symbol,price,volume,cl,hi,lo,funding,oi,prev,source,basis=null}){
 const r1=ret(cl.at(-2),cl.at(-1)),r4=ret(cl.at(-5),cl.at(-1)),r24=ret(cl[0],cl.at(-1)),rv=Math.sqrt(cl.slice(-12).reduce((s,x,i,a)=>i?s+Math.pow(ret(a[i-1],x),2):s,0)/11),range=10000*(Math.max(...hi.slice(-6))-Math.min(...lo.slice(-6)))/cl.at(-1),liq=clip(Math.log10(volume+1)/12,0,1),trend=clip(Math.abs(r4)/(rv*2+1),0,1),volQuality=clip(1-Math.abs(rv-80)/180,0,1),dOi=prev?.openInterest&&oi?100*(oi/prev.openInterest-1):null,technical=.42*r4+.18*r1+.20*r24-.20*Math.sign(r4)*rv,confidence=clip(.38*trend+.34*liq+.28*volQuality,0,1),candidateStrength=Math.abs(technical)*confidence,coverage=[funding,oi,basis].filter(Number.isFinite).length/3,quality=clip(100*(.42*confidence+.28*liq+.18*clip(candidateStrength/80,0,1)+.12*coverage),0,100),action=quality>=62&&candidateStrength>18?(technical>0?'LONG_CANDIDATE':'SHORT_CANDIDATE'):quality>=42?'WATCH':'PASS';
 return{symbol,price,quoteVolume24h:volume,liquidityScore:+(100*liq).toFixed(1),r1Bps:+r1.toFixed(1),r4Bps:+r4.toFixed(1),trendScore:+(100*trend).toFixed(1),rvBps:+rv.toFixed(1),range6hBps:+range.toFixed(1),fundingRate:Number.isFinite(funding)?funding:null,openInterest:Number.isFinite(oi)?oi:null,deltaOiPct:Number.isFinite(dOi)?+dOi.toFixed(3):null,basisBps:Number.isFinite(basis)?+basis.toFixed(2):null,orderFlow:null,depthImbalance:null,liquidations:null,social:null,news:null,fundamental:null,onchain:null,regime:Math.abs(r4)<rv*.7?'RANGE':rv>140?'VOL_EXPANSION':r4>0?'TREND_UP':'TREND_DOWN',modelConfidence:+(100*confidence).toFixed(1),candidateStrength:+candidateStrength.toFixed(1),evidenceCoverage:+(100*coverage).toFixed(1),decisionQuality:+quality.toFixed(1),action,technicalScore:+technical.toFixed(1),source,observedAt:new Date().toISOString()}
}
async function bybitUniverse(limit,previous){const base=process.env.BYBIT_PUBLIC_BASE_URL||'https://api.bybit.com',tk=await j(base+'/v5/market/tickers?category=linear'),rows=(tk.result?.list||[]).filter(x=>x.symbol?.endsWith('USDT')&&num(x.turnover24h)>0).sort((a,b)=>num(b.turnover24h)-num(a.turnover24h)).slice(0,limit);if(!rows.length)throw Error('BYBIT_EMPTY_UNIVERSE');const out=await Promise.all(rows.map(async x=>{try{const k=await j(base+'/v5/market/kline?category=linear&symbol='+x.symbol+'&interval=60&limit=25'),bars=(k.result?.list||[]).slice().reverse(),cl=bars.map(v=>num(v[4])),hi=bars.map(v=>num(v[2])),lo=bars.map(v=>num(v[3]));if(cl.length<14)throw Error('SHORT_HISTORY');return score({symbol:x.symbol,price:num(x.lastPrice),volume:num(x.turnover24h),cl,hi,lo,funding:num(x.fundingRate),oi:num(x.openInterest),prev:previous.get(x.symbol),source:'bybit-linear-public',basis:num(x.indexPrice)?10000*(num(x.markPrice)/num(x.indexPrice)-1):null})}catch{return null}}));return out.filter(Boolean)}
async function okxUniverse(limit,previous){const base=process.env.OKX_PUBLIC_BASE_URL||'https://www.okx.com',tk=await j(base+'/api/v5/market/tickers?instType=SWAP'),rows=(tk.data||[]).filter(x=>x.instId?.endsWith('-USDT-SWAP')&&num(x.volCcy24h)>0).sort((a,b)=>num(b.volCcy24h)-num(a.volCcy24h)).slice(0,limit);if(!rows.length)throw Error('OKX_EMPTY_UNIVERSE');const out=await Promise.all(rows.map(async x=>{try{const [k,oi,fr]=await Promise.all([j(base+'/api/v5/market/history-candles?instId='+x.instId+'&bar=1H&limit=25'),j(base+'/api/v5/public/open-interest?instType=SWAP&instId='+x.instId),j(base+'/api/v5/public/funding-rate?instId='+x.instId)]),bars=(k.data||[]).slice().reverse(),cl=bars.map(v=>num(v[4])),hi=bars.map(v=>num(v[2])),lo=bars.map(v=>num(v[3]));if(cl.length<14)throw Error('SHORT_HISTORY');const symbol=x.instId.replace('-USDT-SWAP','USDT');return score({symbol,price:num(x.last),volume:num(x.volCcy24h)*num(x.last),cl,hi,lo,funding:num(fr.data?.[0]?.fundingRate),oi:num(oi.data?.[0]?.oi),prev:previous.get(symbol),source:'okx-swap-public'})}catch{return null}}));return out.filter(Boolean)}
export async function scanUniverse({limit=60,previous=new Map()}={}){const providers=String(process.env.UNIVERSE_PROVIDERS||'bybit,okx').split(',').map(x=>x.trim()).filter(Boolean),errors=[];for(const p of providers){try{const out=p==='bybit'?await bybitUniverse(limit,previous):p==='okx'?await okxUniverse(limit,previous):null;if(out?.length)return out.sort((a,b)=>b.decisionQuality-a.decisionQuality);throw Error('EMPTY_RESULT')}catch(e){errors.push(p+':'+e.message)}}throw Error('ALL_UNIVERSE_PROVIDERS_FAILED '+errors.join(';'))}
